keycloak:
  auth-server-url: http://62.217.187.145:8484/auth
  realm: SparJob
  resource: spar-job-backend
  ssl-required: external
  use-resource-role-mappings: true
  credentials:
    secret: kR6ZEfa48I6tlSttTjrv5cptVSVe7It4

server:
  port: 8081
